export enum Status {
  WAITING_FOR_PAYMENT = "WAITING_FOR_PAYMENT",
  PAYMENT_CONFIRMATION = "PAYMENT_CONFIRMATION",
  RECIPT_CONFIRMATION = "RECIPT_CONFIRMATION",
  USER_CONFIRMATION = "USER_CONFIRMATION",
  PROCESSING_ORDER = "PROCESSING_ORDER",
  DELIVERY = "DELIVERY",
  COMPLETED = "COMPLETED",
  CANCELED = "CANCELED",
  EXPIRED = "EXPIRED",
  WAITING_FOR_PICKUP = "WAITING_FOR_PICKUP",
  WAITING_FOR_REFUND = "WAITING_FOR_REFUND",
}